name: Android Build

# this runs every time I push to main or make a pull request to main
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # use the latest ubuntu server to run the build
    runs-on: ubuntu-latest

    steps:
      # step 1 — check out the code so the runner can see it
      - name: Checkout code
        uses: actions/checkout@v3

      #  — set up Java 17, which Android projects need
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle


      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # step 4 — actually build the debug version of the app
      - name: Build Debug APK
        run: ./gradlew assembleDebug